# yaml-language-server: $schema=https://www.schemastore.org/github-pages-jekyll.json

description: "Personal multi-skill repository for reusable Codex workflows."
plugins:
    - "jekyll-sitemap"
    - "jekyll-seo-tag"
    - "jekyll-paginate"
    - "jekyll-feed"
    - "jekyll-mentions"
    - "jekyll-avatar"
    - "jekyll-github-metadata"
    - "jekyll-include-cache"
remote_theme: "pages-themes/hacker@v0.2.0"
title: "Codex Skills"
url: "https://nick2bad4u.github.io/codex-skills" # the base hostname & protocol for your site
