name: "Continuous Integration"

run-name: "Continuous Integration • ${{ github.ref_name }} @${{ github.actor }}"

on:
    pull_request:
    push:
        branches:
            - "main"
    merge_group:
        types:
            - "checks_requested"

concurrency:
    group: "ci-${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

permissions:
    contents: "read"
    id-token: "write"

defaults:
    run:
        shell: "bash"

jobs:
    validate:
        name: "Validate"
        runs-on: "ubuntu-latest"
        timeout-minutes: 15
        steps:
            - name: "Checkout"
              uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1

            - name: "Setup Node"
              uses: "actions/setup-node@820762786026740c76f36085b0efc47a31fe5020" # v7.0.0
              with:
                  node-version: "22"
                  cache: "npm"

            - name: "Setup Python"
              uses: "actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97" # v7.0.0
              with:
                  python-version: "3.14"
                  cache: "pip"
                  cache-dependency-path: "requirements-dev.lock"

            - name: "Install Node"
              run: "npm ci --ignore-scripts"

            - name: "Install Python"
              run: "python -m pip install --require-hashes -r requirements-dev.lock"

            - name: "Validate"
              run: "npm run release:verify"

            - name: "Upload Python test results to Codecov"
              if: "${{ !cancelled() }}"
              uses: "codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f" # v7.0.0
              with:
                  use_oidc: true
                  slug: "${{ github.repository }}"
                  files: "coverage/pytest/junit.xml"
                  flags: "python"
                  name: "pytest-junit-python"
                  report_type: "test_results"
                  fail_ci_if_error: true
                  disable_search: true
                  verbose: true

            - name: "Upload Python coverage to Codecov"
              if: "${{ !cancelled() }}"
              uses: "codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f" # v7.0.0
              with:
                  use_oidc: true
                  slug: "${{ github.repository }}"
                  files: "coverage/python/coverage.xml"
                  flags: "python"
                  name: "pytest-coverage-python"
                  report_type: "coverage"
                  fail_ci_if_error: true
                  disable_search: true
                  verbose: true
